In [2]:
#Creating a NumPy array with 6 numbers
import numpy as np
A = np.array([1,2,3,4,5,6])
print(A)

[1 2 3 4 5 6]


In [5]:
#array properties -> dimension, structure, size, data type
print(A.ndim)  
print(A.shape)
print(A.size)
print(A.dtype)

1
(6,)
6
int64


In [7]:
#creating matrix
m = np.array([[20,40],
              [50,70]])
print(m[0,:])
print(m[:,0])


[20 40]
[20 50]


In [13]:
print(A[-1])
print(A[0:5:2])

6
[1 3 5]


In [ ]:
print(A * 3) #multiplying number to numpy array

[ 3  6  9 12 15 18]


In [19]:
arr = np.array([8, 90, 65, 53, 24])
print(arr)
print(" ")
#creating 2x3 matrix
n = np.array([[2,4,9],
              [0,6,3]])
print(n)

[ 8 90 65 53 24]
 
[[2 4 9]
 [0 6 3]]


In [20]:
#accessing elements
print(arr[0])
print(arr[-1])
print(n[1][2])

8
24
3


In [22]:
#slicing 1D array
print(arr[0:3])
print(arr[0:5:2])

[ 8 90 65]
[ 8 65 24]


In [23]:
arr = np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


In [24]:
arr = np.ones((3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [25]:
arr = np.full((2,3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [27]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
ar = np.array([1,2,3,4,5,6,7])
br = ar.copy()

br[2]= 9
print(ar[2])
print(br[2])

3
9


In [11]:
#1D->2D
import numpy as np
arr = np.array([1,6,8,4,2,5,7])
print("1D ARRAY: ")
print(arr,"\n")

print("1D->2D ARRAY: ")
newArr = arr[:, np.newaxis]
print(newArr)

1D ARRAY: 
[1 6 8 4 2 5 7] 

1D->2D ARRAY: 
[[1]
 [6]
 [8]
 [4]
 [2]
 [5]
 [7]]


In [17]:
np.random.randint(1,50, size=5)

array([23, 18, 45, 27, 17], dtype=int32)

In [19]:
arr = np.array([10,5,3,2,9,6]) 
print(arr.max())
print(arr.min())
print(arr.argmax())
print(arr.argmin())

10
2
0
3
